const express = require('express');

function createActivityRoutes(context) {
  const { db, auth, admin, manager, isLeadership, asyncRoute, validHttpUrl, one, ids, activityScope, leadsTeam, belongsToTeam, canManageTeam, managedTeamIds, canManageUser, canManageActivity, visibleActivity, bcrypt, ExcelJS, packageInfo, logger, mailer, push, taskUpload, attachmentKinds, allowedExtensions, attachmentRoot, path, fs, crypto } = context;
  const router = express.Router();

router.patch('/api/activities/:id',auth,manager,asyncRoute(async(req,res,next)=>{if(!Object.hasOwn(req.body,'proposal_document_url'))return next();if(!(await canManageActivity(req.session.user,req.params.id)))return res.status(403).json({error:'You cannot manage this activity.'});const proposalDocumentUrl=String(req.body.proposal_document_url||'').trim();if(!validHttpUrl(proposalDocumentUrl))return res.status(400).json({error:'The activity proposal document must be a valid http:// or https:// link.'});await db.execute('UPDATE activities SET proposal_document_url=? WHERE id=?',[proposalDocumentUrl||null,req.params.id]);delete req.body.proposal_document_url;next()}));

router.get('/api/activities',auth,asyncRoute(async(req,res)=>{const q=`%${String(req.query.q||'')}%`,status=String(req.query.status||'all'),type=String(req.query.type||'all'),s=activityScope(req.session.user);const [rows]=await db.execute(`SELECT a.*,te.name team_name,te.color team_color,u.name creator_name,GROUP_CONCAT(DISTINCT involved.name ORDER BY involved.name SEPARATOR ', ') team_names,COUNT(DISTINCT t.id) task_count,COUNT(DISTINCT CASE WHEN t.status='done' THEN t.id END) done_count,COUNT(DISTINCT p.user_id) participant_count FROM activities a JOIN teams te ON te.id=a.team_id JOIN users u ON u.id=a.creator_id JOIN activity_teams ats ON ats.activity_id=a.id JOIN teams involved ON involved.id=ats.team_id LEFT JOIN tasks t ON t.activity_id=a.id LEFT JOIN participants p ON p.activity_id=a.id AND p.state='confirmed' WHERE ${s.sql} AND (a.title LIKE ? OR a.description LIKE ?) AND (?='all' OR a.status=?) AND (?='all' OR a.type=?) GROUP BY a.id ORDER BY FIELD(a.status,'active','approved','proposed','completed','cancelled'),a.deadline`,[...s.params,q,q,status,status,type,type]);res.json(rows)}));

router.post('/api/activities',auth,manager,asyncRoute(async(req,res)=>{const {title,description,type,start_date,deadline,priority,requested_by,location}=req.body,proposalDocumentUrl=String(req.body.proposal_document_url||'').trim();const teamIds=ids(req.body.team_ids?.length?req.body.team_ids:req.body.team_id),primary=Number(req.body.team_id||teamIds[0]);if(!title||!description||!deadline||!teamIds.length||!teamIds.includes(primary)||!['event','assigned'].includes(type))return res.status(400).json({error:'Complete all required fields and select at least one team.'});if(!validHttpUrl(proposalDocumentUrl))return res.status(400).json({error:'The activity proposal document must be a valid http:// or https:// link.'});if(isLeadership(req.session.user)){for(const teamId of teamIds)if(!(await leadsTeam(req.session.user.id,teamId)))return res.status(403).json({error:'Team leaders and vice leaders may only propose work for teams they lead.'})}const conn=await db.getConnection();try{await conn.beginTransaction();const [result]=await conn.execute('INSERT INTO activities(title,description,proposal_document_url,type,team_id,creator_id,start_date,deadline,priority,requested_by,location) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[title,description,proposalDocumentUrl||null,type,primary,req.session.user.id,start_date||null,deadline,priority||'medium',requested_by||null,location||null]);for(const teamId of teamIds)await conn.execute('INSERT INTO activity_teams(activity_id,team_id,role,responsibility) VALUES(?,?,?,?)',[result.insertId,teamId,teamId===primary?'primary':'supporting',teamId===primary?'Coordinates the activity':'Supports the activity']);await conn.commit();res.status(201).json({id:result.insertId});try{const [admins]=await db.execute("SELECT id,name,email FROM users WHERE role='admin' AND is_active=1");const activity={id:result.insertId,title,type,start_date,deadline,priority:priority||'medium'};for(const adminUser of admins)mailer.notifyActivityProposed(adminUser,activity,req.session.user.name)}catch(error){logger.error(`Unable to prepare activity ${result.insertId} proposal email notifications.`,error)}}catch(e){await conn.rollback();throw e}finally{conn.release()}}));

router.get('/api/activities/:id',auth,asyncRoute(async(req,res)=>{if(!(await visibleActivity(req.session.user,req.params.id)))return res.status(404).json({error:'Activity not found.'});const [[activities],[activityTeams],[tasks],[participants],[updates],[people],[attachments]]=await Promise.all([
  db.execute('SELECT a.*,te.name team_name,te.color team_color,u.name creator_name FROM activities a JOIN teams te ON te.id=a.team_id JOIN users u ON u.id=a.creator_id WHERE a.id=?',[req.params.id]),
  db.execute('SELECT at.*,t.name,t.color,u.name contact_name FROM activity_teams at JOIN teams t ON t.id=at.team_id LEFT JOIN users u ON u.id=at.contact_user_id WHERE at.activity_id=? ORDER BY at.role,t.name',[req.params.id]),
  db.execute(`SELECT t.*,te.name team_name,GROUP_CONCAT(DISTINCT u.name ORDER BY u.name SEPARATOR ', ') assignee_name,GROUP_CONCAT(DISTINCT u.id ORDER BY u.id) assignee_ids FROM tasks t JOIN teams te ON te.id=t.team_id LEFT JOIN task_assignees ta ON ta.task_id=t.id LEFT JOIN users u ON u.id=ta.user_id WHERE t.activity_id=? GROUP BY t.id ORDER BY FIELD(t.stage,'before','during','after','general'),t.deadline`,[req.params.id]),
  db.execute("SELECT p.*,u.name,u.role,u.avatar_color FROM participants p JOIN users u ON u.id=p.user_id WHERE p.activity_id=? ORDER BY FIELD(p.state,'confirmed','volunteered','declined'),u.name",[req.params.id]),
  db.execute('SELECT n.*,u.name user_name,u.avatar_color FROM updates n JOIN users u ON u.id=n.user_id WHERE n.activity_id=? ORDER BY n.created_at DESC',[req.params.id]),
  db.execute("SELECT u.id,u.name,u.role,MIN(ut.team_id) team_id,GROUP_CONCAT(DISTINCT t.id ORDER BY t.id) team_ids,GROUP_CONCAT(DISTINCT t.name ORDER BY t.name SEPARATOR ', ') teams FROM users u LEFT JOIN user_teams ut ON ut.user_id=u.id LEFT JOIN teams t ON t.id=ut.team_id LEFT JOIN activity_teams at ON at.team_id=ut.team_id WHERE u.is_active=1 AND (?='admin' OR (at.activity_id=? AND EXISTS(SELECT 1 FROM user_teams lead_team WHERE lead_team.user_id=? AND lead_team.team_id=ut.team_id AND (lead_team.is_lead=1 OR lead_team.is_vice_lead=1)))) GROUP BY u.id ORDER BY u.name",[req.session.user.role,req.params.id,req.session.user.id]),
  db.execute('SELECT x.id,x.task_id,x.kind,x.label,x.link_url,x.original_name,x.mime_type,x.size_bytes,x.created_at,u.name user_name FROM task_attachments x JOIN users u ON u.id=x.user_id JOIN tasks t ON t.id=x.task_id WHERE t.activity_id=? ORDER BY x.created_at DESC',[req.params.id])
]);const activity=activities[0];for(const task of tasks){task.recorded_stage=task.stage;if(activity.type==='assigned')task.stage='general';else if(task.stage==='general')task.stage='before'}for(const person of people){person.team_ids=String(person.team_ids||'').split(',').filter(Boolean).map(Number);person.team_names=String(person.teams||'').split(',').map(x=>x.trim()).filter(Boolean)}res.json({activity,activityTeams,tasks,participants,updates,people,attachments,canManage:await canManageActivity(req.session.user,req.params.id)})}));

router.patch('/api/activities/:id',auth,manager,asyncRoute(async(req,res)=>{if(!(await canManageActivity(req.session.user,req.params.id)))return res.status(403).json({error:'You cannot manage this activity.'});const teamEdit=req.body.team_ids!==undefined||req.body.team_id!==undefined;if(teamEdit&&req.session.user.role!=='admin')return res.status(403).json({error:'Only administrators can change involved teams.'});const allowed=['status','priority','result_summary','title','description','type','deadline','start_date','location','requested_by'];const entries=Object.entries(req.body).filter(([key])=>allowed.includes(key));if(['title','description','deadline'].some(key=>Object.hasOwn(req.body,key)&&!String(req.body[key]||'').trim()))return res.status(400).json({error:'Title, description and deadline cannot be empty.'});let teamIds=[],primary=0;if(teamEdit){teamIds=ids(req.body.team_ids),primary=Number(req.body.team_id);if(!teamIds.length||!teamIds.includes(primary))return res.status(400).json({error:'Select involved teams and a coordinating team.'});const [validTeams]=await db.query(`SELECT id FROM teams WHERE is_active=1 AND id IN (${teamIds.map(()=>'?').join(',')})`,teamIds);if(validTeams.length!==teamIds.length)return res.status(400).json({error:'One or more selected teams are unavailable.'});const [taskTeams]=await db.query(`SELECT DISTINCT team_id FROM tasks WHERE activity_id=? AND team_id NOT IN (${teamIds.map(()=>'?').join(',')})`,[req.params.id,...teamIds]);if(taskTeams.length)return res.status(409).json({error:'A team with existing tasks cannot be removed. Reassign those tasks first.'})}if(!entries.length&&!teamEdit)return res.status(400).json({error:'No valid fields supplied.'});const conn=await db.getConnection();try{await conn.beginTransaction();if(entries.length)await conn.execute(`UPDATE activities SET ${entries.map(([k])=>`${k}=?`).join(',')} WHERE id=?`,[...entries.map(([k,v])=>['start_date','location','requested_by','result_summary'].includes(k)?v||null:v),req.params.id]);if(teamEdit){await conn.execute('UPDATE activities SET team_id=? WHERE id=?',[primary,req.params.id]);for(const teamId of teamIds)await conn.execute("INSERT INTO activity_teams(activity_id,team_id,role,responsibility) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE role=VALUES(role)",[req.params.id,teamId,teamId===primary?'primary':'supporting',teamId===primary?'Coordinates the activity':'Supports the activity']);await conn.query(`DELETE FROM activity_teams WHERE activity_id=? AND team_id NOT IN (${teamIds.map(()=>'?').join(',')})`,[req.params.id,...teamIds]);await conn.execute("UPDATE activity_teams SET role=IF(team_id=?,'primary','supporting') WHERE activity_id=?",[primary,req.params.id])}await conn.commit();res.json({ok:true})}catch(e){await conn.rollback();throw e}finally{conn.release()}}));
router.post('/api/activities/:id/volunteer',auth,asyncRoute(async(req,res)=>{if(!(await visibleActivity(req.session.user,req.params.id)))return res.status(404).json({error:'Activity not found.'});await db.execute("INSERT INTO participants(activity_id,user_id,state) VALUES(?,?,'volunteered') ON DUPLICATE KEY UPDATE state='volunteered'",[req.params.id,req.session.user.id]);res.json({ok:true})}));
router.post('/api/activities/:id/participants',auth,manager,asyncRoute(async(req,res)=>{if(!(await canManageActivity(req.session.user,req.params.id)))return res.status(403).json({error:'You cannot manage participants for this activity.'});const userIds=ids(req.body.user_ids);if(!userIds.length)return res.status(400).json({error:'Select at least one member.'});for(const userId of userIds){let sql='SELECT 1 FROM users WHERE id=? AND is_active=1',params=[userId];if(isLeadership(req.session.user)){sql='SELECT 1 FROM users u JOIN user_teams member_team ON member_team.user_id=u.id JOIN user_teams leader_team ON leader_team.team_id=member_team.team_id AND leader_team.user_id=? AND (leader_team.is_lead=1 OR leader_team.is_vice_lead=1) JOIN activity_teams at ON at.team_id=member_team.team_id AND at.activity_id=? WHERE u.id=? AND u.is_active=1 LIMIT 1';params=[req.session.user.id,req.params.id,userId]}const [eligible]=await db.execute(sql,params);if(!eligible.length)return res.status(403).json({error:'You may only add active members from teams you lead.'})}const responsibility=String(req.body.responsibility||'Activity participant').trim().slice(0,255);const marks=userIds.map(()=>'?').join(',');const [[existing],[users],[activities]]=await Promise.all([db.query(`SELECT user_id,state FROM participants WHERE activity_id=? AND user_id IN (${marks})`,[req.params.id,...userIds]),db.query(`SELECT id,name,email FROM users WHERE id IN (${marks})`,userIds),db.execute('SELECT id,title,deadline FROM activities WHERE id=?',[req.params.id])]);for(const userId of userIds)await db.execute("INSERT INTO participants(activity_id,user_id,state,responsibility) VALUES(?,?,'confirmed',?) ON DUPLICATE KEY UPDATE state='confirmed',responsibility=VALUES(responsibility)",[req.params.id,userId,responsibility]);res.status(201).json({ok:true});const confirmed=new Set(existing.filter(item=>item.state==='confirmed').map(item=>Number(item.user_id)));for(const user of users)if(!confirmed.has(Number(user.id)))mailer.notifyActivityRegistration(user,activities[0],responsibility,req.session.user.name)}));
router.post('/api/activities/:id/updates',auth,asyncRoute(async(req,res)=>{if(!(await visibleActivity(req.session.user,req.params.id)))return res.status(404).json({error:'Activity not found.'});const body=String(req.body.body||'').trim(),taskId=Number(req.body.task_id)||null,kind=req.body.kind||'comment';if(!body)return res.status(400).json({error:'Write an update first.'});await db.execute('INSERT INTO updates(activity_id,task_id,user_id,body,kind,attachment_url) VALUES(?,?,?,?,?,?)',[req.params.id,taskId,req.session.user.id,body,kind,req.body.attachment_url||null]);res.status(201).json({ok:true});if(taskId)try{const [[tasks],[owners]]=await Promise.all([db.execute('SELECT t.id,t.title,t.activity_id,a.title activity_title FROM tasks t JOIN activities a ON a.id=t.activity_id WHERE t.id=? AND t.activity_id=?',[taskId,req.params.id]),db.execute('SELECT DISTINCT u.id,u.name,u.email FROM users u JOIN tasks t ON t.id=? LEFT JOIN task_assignees ta ON ta.task_id=t.id AND ta.user_id=u.id WHERE u.is_active=1 AND u.id!=? AND (ta.user_id IS NOT NULL OR u.id=t.assigned_by)',[taskId,req.session.user.id])]);const task=tasks[0];if(task)for(const owner of owners)mailer.notifyTaskResponse(owner,task,req.session.user.name,{body,kind})}catch(error){logger.error(`Unable to prepare task ${taskId} response push notifications.`,error)}}));

router.post('/api/activities/:id/tasks',auth,manager,asyncRoute(async(req,res)=>{if(!(await canManageActivity(req.session.user,req.params.id)))return res.status(403).json({error:'You cannot manage this activity.'});const {title,description,stage,priority,team_id,start_date,deadline,deliverable}=req.body,assigneeIds=ids(req.body.assignee_ids?.length?req.body.assignee_ids:req.body.assignee_id);if(!title||!team_id||!deadline)return res.status(400).json({error:'Title, team and deadline are required.'});if(!(await canManageTeam(req.session.user,team_id)))return res.status(403).json({error:'You cannot assign work for this team.'});for(const userId of assigneeIds){const [member]=await db.execute('SELECT 1 FROM user_teams WHERE user_id=? AND team_id=?',[userId,team_id]);if(!member.length)return res.status(400).json({error:'Every assignee must belong to the responsible team.'})}const conn=await db.getConnection();try{await conn.beginTransaction();const [result]=await conn.execute('INSERT INTO tasks(activity_id,title,description,stage,priority,team_id,assignee_id,assigned_by,start_date,deadline,deliverable) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[req.params.id,title,description||null,stage||'general',priority||'medium',team_id,assigneeIds[0]||null,req.session.user.id,start_date||null,deadline,deliverable||null]);for(const userId of assigneeIds)await conn.execute('INSERT INTO task_assignees(task_id,user_id) VALUES(?,?)',[result.insertId,userId]);await conn.execute("INSERT IGNORE INTO activity_teams(activity_id,team_id,role,responsibility) VALUES(?,?,'supporting','Responsible for assigned work')",[req.params.id,team_id]);await conn.commit();res.status(201).json({id:result.insertId});if(assigneeIds.length)try{const marks=assigneeIds.map(()=>'?').join(',');const [[users],[activities]]=await Promise.all([db.query(`SELECT id,name,email FROM users WHERE id IN (${marks})`,assigneeIds),db.execute('SELECT title FROM activities WHERE id=?',[req.params.id])]);const task={id:result.insertId,activity_id:Number(req.params.id),activity_title:activities[0]?.title||'Hoáº¡t Ä‘á»™ng',title,deadline,priority:priority||'medium',deliverable};for(const user of users)mailer.notifyTaskAssigned(user,task,req.session.user.name)}catch(error){logger.error(`Unable to prepare task ${result.insertId} push notifications.`,error)}}catch(e){await conn.rollback();throw e}finally{conn.release()}}));

  return router;
}

module.exports = { createActivityRoutes };

