const express = require('express');

function createTaskRoutes(context) {
  const { db, auth, admin, manager, isLeadership, asyncRoute, validHttpUrl, one, ids, activityScope, leadsTeam, belongsToTeam, canManageTeam, managedTeamIds, canManageUser, canManageActivity, visibleActivity, bcrypt, ExcelJS, packageInfo, logger, mailer, push, taskUpload, attachmentKinds, allowedExtensions, attachmentRoot, path, fs, crypto } = context;
  const router = express.Router();

router.patch('/api/tasks/:id',auth,asyncRoute(async(req,res)=>{const [rows]=await db.execute('SELECT t.*,EXISTS(SELECT 1 FROM task_assignees ta WHERE ta.task_id=t.id AND ta.user_id=?) assigned_to_me FROM tasks t WHERE t.id=?',[req.session.user.id,req.params.id]);const task=one(rows);if(!task)return res.status(404).json({error:'Task not found.'});const manages=await canManageTeam(req.session.user,task.team_id);if(!manages&&!task.assigned_to_me)return res.status(403).json({error:'You cannot update this task.'});const allowed=manages?['status','deadline','start_date','priority','deliverable']:['status'];const entries=Object.entries(req.body).filter(([key])=>allowed.includes(key));if(!entries.length)return res.status(400).json({error:'No valid fields supplied.'});const complete=entries.find(([k])=>k==='status')?.[1]==='done'?',completed_at=NOW()':'';await db.execute(`UPDATE tasks SET ${entries.map(([k])=>`${k}=?`).join(',')}${complete} WHERE id=?`,[...entries.map(([,v])=>v||null),req.params.id]);res.json({ok:true})}));

router.post('/api/tasks/:id/attachments',auth,taskUpload.single('file'),asyncRoute(async(req,res)=>{const [tasks]=await db.execute('SELECT id,activity_id FROM tasks WHERE id=?',[req.params.id]);const task=one(tasks);if(!task||!(await visibleActivity(req.session.user,task.activity_id)))return res.status(404).json({error:'Task not found.'});const kind=attachmentKinds.includes(req.body.kind)?req.body.kind:'clarification';const linkUrl=String(req.body.link_url||'').trim();if(linkUrl&&!/^https?:\/\//i.test(linkUrl))return res.status(400).json({error:'Links must begin with http:// or https://.'});if(!req.file&&!linkUrl)return res.status(400).json({error:'Choose a file or provide a relevant link.'});let storedName=null;try{if(req.file){const ext=path.extname(req.file.originalname).toLowerCase();if(!allowedExtensions.has(ext))return res.status(415).json({error:'This file type is not supported.'});const [usageRows]=await db.execute('SELECT COALESCE(SUM(size_bytes),0) used FROM task_attachments WHERE task_id=?',[task.id]);if(Number(usageRows[0].used)+req.file.size>50*1024*1024)return res.status(413).json({error:'This task has reached its shared 50 MB upload limit.'});storedName=`${task.id}-${crypto.randomUUID()}${ext}`;await fs.promises.writeFile(path.join(attachmentRoot,storedName),req.file.buffer,{flag:'wx'})}const label=String(req.body.label||req.file?.originalname||linkUrl).trim().slice(0,180);const [result]=await db.execute('INSERT INTO task_attachments(task_id,user_id,kind,label,link_url,stored_name,original_name,mime_type,size_bytes) VALUES(?,?,?,?,?,?,?,?,?)',[task.id,req.session.user.id,kind,label,linkUrl||null,storedName,req.file?.originalname||null,req.file?.mimetype||null,req.file?.size||0]);res.status(201).json({id:result.insertId})}catch(e){if(storedName)await fs.promises.unlink(path.join(attachmentRoot,storedName)).catch(()=>{});throw e}}));

router.get('/api/task-attachments/:id/content',auth,asyncRoute(async(req,res)=>{const [rows]=await db.execute('SELECT x.*,t.activity_id FROM task_attachments x JOIN tasks t ON t.id=x.task_id WHERE x.id=?',[req.params.id]);const item=one(rows);if(!item||!item.stored_name||!(await visibleActivity(req.session.user,item.activity_id)))return res.status(404).json({error:'Attachment not found.'});const filePath=path.join(attachmentRoot,path.basename(item.stored_name));if(!fs.existsSync(filePath))return res.status(404).json({error:'Stored file not found.'});res.type(item.mime_type||'application/octet-stream');res.setHeader('Content-Disposition',`${String(item.mime_type||'').startsWith('image/')?'inline':'attachment'}; filename*=UTF-8''${encodeURIComponent(item.original_name)}`);res.sendFile(filePath)}));

router.get('/api/tasks/:id',auth,asyncRoute(async(req,res)=>{const [taskRows]=await db.execute(`SELECT t.*,a.title activity_title,a.description activity_description,a.status activity_status,a.deadline activity_deadline,te.name team_name,GROUP_CONCAT(DISTINCT u.name ORDER BY u.name SEPARATOR ', ') assignee_name,GROUP_CONCAT(DISTINCT u.id ORDER BY u.id) assignee_ids FROM tasks t JOIN activities a ON a.id=t.activity_id JOIN teams te ON te.id=t.team_id LEFT JOIN task_assignees ta ON ta.task_id=t.id LEFT JOIN users u ON u.id=ta.user_id WHERE t.id=? GROUP BY t.id`,[req.params.id]);const task=one(taskRows);if(!task||!(await visibleActivity(req.session.user,task.activity_id)))return res.status(404).json({error:'Task not found.'});const [[attachments],[updates]]=await Promise.all([db.execute('SELECT x.id,x.task_id,x.kind,x.label,x.link_url,x.original_name,x.mime_type,x.size_bytes,x.created_at,u.name user_name FROM task_attachments x JOIN users u ON u.id=x.user_id WHERE x.task_id=? ORDER BY x.created_at DESC',[task.id]),db.execute('SELECT n.*,u.name user_name,u.avatar_color FROM updates n JOIN users u ON u.id=n.user_id WHERE n.task_id=? ORDER BY n.created_at DESC',[task.id])]);const assigned=String(task.assignee_ids||'').split(',').map(Number).includes(req.session.user.id),manages=await canManageTeam(req.session.user,task.team_id);res.json({task,attachments,updates,canUpdate:assigned||manages})}));

  return router;
}

module.exports = { createTaskRoutes };

