const express = require('express');

function createTeamRoutes(context) {
  const { db, auth, admin, manager, isLeadership, asyncRoute, validHttpUrl, one, ids, activityScope, leadsTeam, belongsToTeam, canManageTeam, managedTeamIds, canManageUser, canManageActivity, visibleActivity, bcrypt, ExcelJS, packageInfo, logger, mailer, push, taskUpload, attachmentKinds, allowedExtensions, attachmentRoot, path, fs, crypto } = context;
  const router = express.Router();

router.get('/api/teams',auth,asyncRoute(async(req,res)=>{const [rows]=await db.execute(`SELECT t.*,COUNT(DISTINCT ut.user_id) member_count,COUNT(DISTINCT CASE WHEN a.status IN ('approved','active') THEN ats.activity_id END) active_count,EXISTS(SELECT 1 FROM user_teams mine WHERE mine.team_id=t.id AND mine.user_id=? AND (mine.is_lead=1 OR mine.is_vice_lead=1)) can_manage FROM teams t LEFT JOIN user_teams ut ON ut.team_id=t.id LEFT JOIN activity_teams ats ON ats.team_id=t.id LEFT JOIN activities a ON a.id=ats.activity_id WHERE t.is_active=1 GROUP BY t.id ORDER BY t.sort_order,t.name`,[req.session.user.id]);res.json(rows)}));
router.post('/api/teams',auth,admin,asyncRoute(async(req,res)=>{if(!req.body.name)return res.status(400).json({error:'Team name is required.'});const [result]=await db.execute('INSERT INTO teams(name,description,color) VALUES(?,?,?)',[req.body.name,req.body.description||null,req.body.color||'#315C4C']);res.status(201).json({id:result.insertId})}));
router.patch('/api/teams/:id',auth,manager,asyncRoute(async(req,res)=>{if(!(await canManageTeam(req.session.user,req.params.id)))return res.status(403).json({error:'You cannot edit this team.'});const color=String(req.body.color||'');if(!/^#[0-9a-f]{6}$/i.test(color))return res.status(400).json({error:'Choose a valid team color.'});const fields=['color=?'],values=[color];if(req.session.user.role==='admin'){if(!String(req.body.name||'').trim())return res.status(400).json({error:'Team name is required.'});fields.push('name=?','description=?');values.push(String(req.body.name).trim(),String(req.body.description||'').trim()||null)}values.push(req.params.id);await db.execute(`UPDATE teams SET ${fields.join(',')} WHERE id=?`,values);res.json({ok:true})}));
router.get('/api/teams/:id/members',auth,asyncRoute(async(req,res)=>{if(req.session.user.role!=='admin'&&!(await canManageTeam(req.session.user,req.params.id)))return res.status(403).json({error:'You cannot manage this team.'});const [[members],[available]]=await Promise.all([db.execute('SELECT u.id,u.name,u.email,u.role,u.avatar_color,ut.is_lead,ut.is_vice_lead FROM user_teams ut JOIN users u ON u.id=ut.user_id WHERE ut.team_id=? AND u.is_active=1 ORDER BY ut.is_lead DESC,ut.is_vice_lead DESC,u.name',[req.params.id]),db.execute('SELECT u.id,u.name,u.email,u.role FROM users u WHERE u.is_active=1 AND NOT EXISTS(SELECT 1 FROM user_teams ut WHERE ut.user_id=u.id AND ut.team_id=?) ORDER BY u.name',[req.params.id])]);res.json({members,available})}));
router.get('/api/teams/:id/overview',auth,asyncRoute(async(req,res)=>{if(req.session.user.role!=='admin'&&!(await canManageTeam(req.session.user,req.params.id)))return res.status(403).json({error:'You cannot view this team overview.'});const [[teamRows],[members],[tasks],[activities]]=await Promise.all([db.execute(`SELECT t.*,COUNT(DISTINCT ut.user_id) member_count,COUNT(DISTINCT CASE WHEN tk.status!='done' THEN tk.id END) open_tasks,COUNT(DISTINCT CASE WHEN tk.status='done' THEN tk.id END) done_tasks,COUNT(DISTINCT CASE WHEN tk.status!='done' AND tk.deadline<CURDATE() THEN tk.id END) overdue_tasks FROM teams t LEFT JOIN user_teams ut ON ut.team_id=t.id LEFT JOIN tasks tk ON tk.team_id=t.id WHERE t.id=? GROUP BY t.id`,[req.params.id]),db.execute(`SELECT u.id,u.name,u.email,u.role,u.avatar_color,ut.is_lead,ut.is_vice_lead,COUNT(DISTINCT CASE WHEN tk.status!='done' THEN ta.task_id END) open_tasks,COUNT(DISTINCT CASE WHEN tk.status='done' THEN ta.task_id END) done_tasks FROM user_teams ut JOIN users u ON u.id=ut.user_id LEFT JOIN task_assignees ta ON ta.user_id=u.id LEFT JOIN tasks tk ON tk.id=ta.task_id AND tk.team_id=ut.team_id WHERE ut.team_id=? AND u.is_active=1 GROUP BY u.id,ut.is_lead,ut.is_vice_lead ORDER BY ut.is_lead DESC,ut.is_vice_lead DESC,u.name`,[req.params.id]),db.execute(`SELECT tk.*,a.title activity_title,GROUP_CONCAT(DISTINCT u.name ORDER BY u.name SEPARATOR ', ') assignee_name FROM tasks tk JOIN activities a ON a.id=tk.activity_id LEFT JOIN task_assignees ta ON ta.task_id=tk.id LEFT JOIN users u ON u.id=ta.user_id WHERE tk.team_id=? GROUP BY tk.id ORDER BY FIELD(tk.status,'in_progress','review','open','done'),tk.deadline LIMIT 50`,[req.params.id]),db.execute(`SELECT a.id,a.title,a.status,a.deadline,ats.role,COUNT(DISTINCT tk.id) task_count,COUNT(DISTINCT CASE WHEN tk.status='done' THEN tk.id END) done_count FROM activity_teams ats JOIN activities a ON a.id=ats.activity_id LEFT JOIN tasks tk ON tk.activity_id=a.id AND tk.team_id=ats.team_id WHERE ats.team_id=? GROUP BY a.id,ats.role ORDER BY FIELD(a.status,'active','approved','proposed','completed','cancelled'),a.deadline`,[req.params.id])]);if(!teamRows.length)return res.status(404).json({error:'Team not found.'});res.json({team:teamRows[0],members,tasks,activities})}));
router.patch('/api/teams/:id/members/:userId',auth,admin,asyncRoute(async(req,res)=>{const teamRole=String(req.body.team_role||'member');if(!['member','vice_leader','leader'].includes(teamRole))return res.status(400).json({error:'Choose a valid team role.'});const [result]=await db.execute('UPDATE user_teams SET is_lead=?,is_vice_lead=? WHERE team_id=? AND user_id=?',[teamRole==='leader',teamRole==='vice_leader',req.params.id,req.params.userId]);if(!result.affectedRows)return res.status(404).json({error:'Team membership not found.'});const [leadership]=await db.execute('SELECT MAX(is_lead) is_lead,MAX(is_vice_lead) is_vice_lead FROM user_teams WHERE user_id=?',[req.params.userId]);const current=leadership[0],role=current.is_lead?'leader':current.is_vice_lead?'vice_leader':'member';await db.execute("UPDATE users SET role=? WHERE id=? AND role!='admin'",[role,req.params.userId]);res.json({ok:true,role})}));
router.post('/api/teams/:id/members',auth,manager,asyncRoute(async(req,res)=>{if(!(await canManageTeam(req.session.user,req.params.id)))return res.status(403).json({error:'You cannot manage this team.'});const userId=Number(req.body.user_id),teamRole=req.session.user.role==='admin'?String(req.body.team_role||'member'):'member';const [users]=await db.execute('SELECT role FROM users WHERE id=? AND is_active=1',[userId]);if(!users.length)return res.status(404).json({error:'User not found.'});if(!['member','vice_leader','leader'].includes(teamRole))return res.status(400).json({error:'Choose a valid team role.'});if(isLeadership(req.session.user)&&users[0].role!=='member')return res.status(403).json({error:'Team leaders and vice leaders may only add member accounts.'});const isLead=teamRole==='leader',isViceLead=teamRole==='vice_leader';await db.execute('INSERT INTO user_teams(user_id,team_id,is_lead,is_vice_lead) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE is_lead=VALUES(is_lead),is_vice_lead=VALUES(is_vice_lead)',[userId,req.params.id,isLead,isViceLead]);if((isLead||isViceLead)&&users[0].role==='member')await db.execute('UPDATE users SET role=? WHERE id=?',[teamRole,userId]);res.status(201).json({ok:true})}));

  return router;
}

module.exports = { createTeamRoutes };

