'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const mysql=require('mysql2/promise');
const {chromium}=require('@playwright/test');
require('dotenv').config({path:path.resolve(__dirname,'../../.env.local'),quiet:true});
process.env.WORKSPACE_DB_NAME='seee_workspace_browser';
process.env.LOCAL_DEMO_AUTH='true';
const {seed}=require('../../scripts/local/seed');
const {createApplication}=require('../../src/workspace/app');
let root,app,server,browser;
(async()=>{
 const credentials=JSON.parse(fs.readFileSync(path.resolve(__dirname,'../../.local/mysql-admin.json'),'utf8'));
 root=await mysql.createConnection({host:'127.0.0.1',port:3307,user:'root',password:credentials.password,multipleStatements:true});
 const [[r]]=await root.query('SELECT @@datadir directory');assert.equal(path.resolve(r.directory).toLowerCase(),path.resolve(__dirname,'../../.local/mysql-data').toLowerCase());
 await root.query('DROP DATABASE IF EXISTS seee_workspace_browser');await root.query('CREATE DATABASE seee_workspace_browser CHARACTER SET utf8mb4');
 await root.query("GRANT ALL ON seee_workspace_browser.* TO 'seee_local'@'localhost'");await root.query('USE seee_workspace_browser');await seed(root);
 app=createApplication();await new Promise(r=>{server=app.app.listen(0,'127.0.0.1',r);});
 const base=`http://127.0.0.1:${server.address().port}`;
 browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1050}});await page.addInitScript(()=>{if(!localStorage.getItem('workspace-language'))localStorage.setItem('workspace-language','en');});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 async function login(role){await page.goto(base);await page.getByRole('button',{name:role,exact:true}).click();await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('heading',{name:'Overview',exact:true}).waitFor();}
 async function logout(){await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.getByRole('button',{name:'Sign in',exact:true}).waitFor();}
 await login('Member');
 await page.screenshot({path:'.local/workspace-desktop.png',fullPage:true});
 assert.equal(await page.getByRole('link',{name:'Admin Center',exact:true}).count(),0);
 await page.getByRole('link',{name:'Activities',exact:true}).first().click();await page.getByRole('heading',{name:'Activities',exact:true}).waitFor();
 await page.getByRole('button',{name:'New record',exact:true}).click();
 await page.locator('#record-form [name=title]').fill('Browser-created workshop');await page.locator('#record-form [name=body]').fill('A synthetic test created through the browser.');
 await page.locator('#audience-mode').selectOption('teams');await page.locator('[name=audience_team][value="4"]').check();
 await page.getByRole('button',{name:'Save draft',exact:true}).click();await page.getByRole('heading',{name:'Browser-created workshop',exact:true}).waitFor();
 await page.getByRole('button',{name:'Submit for approval',exact:true}).click();await page.locator('.detail-hero .badge.pending').waitFor();
 await logout();await login('Leader');await page.getByRole('link',{name:'Approvals',exact:true}).click();
 const request=page.locator('.approval').filter({has:page.getByRole('heading',{name:'Browser-created workshop',exact:true})});await request.getByRole('button',{name:'Approve',exact:true}).click();
 await page.locator('#decision-form [name=note]').fill('Approved in browser smoke test.');await page.locator('#decision-form button[type=submit]').click();await page.locator('#modal').waitFor({state:'hidden'});await request.waitFor({state:'hidden'});const [[decisionState]]=await root.query("SELECT i.state FROM workflow_instances i JOIN records r ON r.id=i.record_id WHERE r.title='Browser-created workshop'");assert.equal(decisionState.state,'approved');
 await page.getByRole('link',{name:'Teams & units',exact:true}).click();const team=page.locator('.card').filter({has:page.getByRole('heading',{name:'Electrical Engineering',exact:true})});await team.getByRole('button',{name:'Appoint member / leader',exact:true}).click();await page.locator('#appointment-form [name=user_id]').selectOption('6');await page.locator('#appointment-form [name=role]').selectOption('leader');await page.locator('#appointment-form button[type=submit]').click();await page.locator('#modal').waitFor({state:'hidden'});
 await logout();await login('Public');await page.goto(base+'/#record/3');await page.getByRole('heading',{name:'Leadership planning discussion',exact:true}).waitFor();
 await logout();await login('Dean');await page.goto(base+'/#record/6');await page.getByRole('heading',{name:'Unable to open this page'}).waitFor();
 await logout();await login('Administrator');await page.getByRole('link',{name:'Admin Center',exact:true}).click();await page.locator('.matrix').waitFor();
 await page.screenshot({path:'.local/workspace-admin.png',fullPage:true});
 await page.getByRole('button',{name:'Workflows',exact:true}).click();await page.getByRole('button',{name:'Publish workflow version',exact:true}).click();
 await page.locator('#workflow-form [name=unit_id]').selectOption('4');await page.locator('[name=step_role]').selectOption('3');await page.locator('[name=step_scope]').selectOption('owner');
 await page.locator('#workflow-form button[type=submit]').click();await page.locator('#modal').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'Audit & reports',exact:true}).click();const downloaded=page.waitForEvent('download');await page.getByRole('link',{name:'Export history',exact:true}).click();assert.match((await downloaded).suggestedFilename(),/xlsx$/);
 await page.goto(base+'/#rooms');await page.getByRole('heading',{name:'Mượn phòng',exact:true}).waitFor();
 await page.getByRole('button',{name:'Thêm phòng',exact:true}).click();
 await page.locator('#room-config-form [name=name]').fill('Browser room');await page.locator('#room-config-form [name=location]').fill('Building A');
 await page.locator('#room-config-form button[type=submit]').click();await page.locator('#modal').waitFor({state:'hidden'});
 await root.query("INSERT INTO unit_roles(user_id,unit_id,role_id) SELECT 5,4,id FROM roles WHERE code='faculty'");
 await logout();await login('Member');await page.getByRole('link',{name:'Requests',exact:true}).click();await page.getByRole('link',{name:/Room booking/}).click();await page.getByRole('heading',{name:'Mượn phòng',exact:true}).waitFor();
 await page.getByRole('button',{name:'Đăng ký phòng',exact:true}).click();
 await page.locator('#room-book-form [name=date]').fill('2099-01-05');await page.locator('#room-book-form [name=chair]').fill('Test chair');await page.locator('#room-book-form [name=agenda]').fill('Browser meeting');
 await page.locator('#room-book-form button[type=submit]').click();await page.locator('#modal').waitFor({state:'hidden'});await page.getByText('Browser meeting',{exact:true}).waitFor();
 await page.screenshot({path:'.local/workspace-rooms.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false,'room calendar mobile overflow');
 await page.setViewportSize({width:390,height:844});await page.goto(base+'/#overview');await page.getByRole('heading',{name:'Overview',exact:true}).waitFor();
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);assert.equal(overflow,false,'mobile horizontal overflow');
 await page.screenshot({path:'.local/workspace-mobile.png',fullPage:true});
 await page.getByRole('button',{name:'Open navigation'}).click();await page.getByRole('link',{name:'Documents',exact:true}).click();await page.getByRole('heading',{name:'Documents',exact:true}).waitFor();
 await page.getByRole('button',{name:'EN',exact:true}).click();await page.getByRole('heading',{name:'Tài liệu',exact:true}).waitFor();
 // Vietnamese interface, tools navigation, and search must work together.
 await page.setViewportSize({width:1440,height:1050});
 await page.getByRole('button',{name:'Đăng xuất',exact:true}).click();
 await page.getByRole('button',{name:'Quản trị viên',exact:true}).click();
 await page.getByRole('button',{name:'Đăng nhập',exact:true}).click();
 await page.getByRole('heading',{name:'Tổng quan',exact:true}).waitFor();
 assert.equal(await page.locator('.nav a[href="#rooms"]').count(),0);
 await page.getByRole('link',{name:'Đề nghị',exact:true}).click();
 await page.getByRole('link',{name:/Tạo đề nghị/}).click();
 await page.locator('#search-form').waitFor();
 await page.getByRole('link',{name:/Về danh sách công cụ đề nghị/}).click();
 await page.getByRole('link',{name:/Mượn phòng/}).click();
 await page.getByRole('heading',{name:'Mượn phòng',exact:true}).waitFor();
 assert.equal(await page.locator('.nav a.active').getAttribute('href'),'#requests');
 await page.getByRole('link',{name:'Trung tâm quản trị',exact:true}).click();
 await page.getByRole('searchbox',{name:'Tìm vai trò',exact:true}).fill('giang vien');
 assert.equal(await page.locator('.matrix thead th:visible').count(),2);
 assert.match(await page.locator('.matrix thead').innerText(),/Giảng viên/);
 await page.getByRole('searchbox',{name:'Tìm vai trò',exact:true}).fill('');
 await page.getByRole('searchbox',{name:'Tìm quyền',exact:true}).fill('muon phong');
 assert.equal(await page.locator('.matrix tbody tr:visible').count(),1);
 await page.getByRole('button',{name:'Người dùng & quyền',exact:true}).click();
 await page.getByRole('searchbox',{name:'Tìm trong danh sách',exact:true}).fill('coleader.demo');
 assert.equal(await page.locator('tbody tr:visible').count(),1);
 await page.getByRole('searchbox',{name:'Tìm trong danh sách',exact:true}).fill('no-such-person');
 await page.getByText('Không có kết quả phù hợp',{exact:true}).waitFor();
 await page.getByRole('searchbox',{name:'Tìm trong danh sách',exact:true}).fill('');
 await page.getByRole('combobox',{name:'Vai trò',exact:true}).selectOption('1');
 assert.equal(await page.locator('tbody tr:visible').count(),2);
 await page.getByRole('button',{name:'Gán vai trò',exact:true}).click();
 const picker=page.locator('#assignment-form label').first();
 assert.match(await picker.innerText(),/office\.demo@hust\.edu\.vn/,'localization must preserve email addresses');
 await picker.getByRole('searchbox').fill('coleader.demo');
 assert.equal(await picker.locator('option').count(),2,'matching option and current selection remain');
 await page.getByRole('button',{name:'Đóng hộp thoại',exact:true}).click();
 for(const tab of ['roles','people','workflows','units','audit']){
  await page.locator(`[data-tab="${tab}"]`).click();
  await page.locator('#content table').waitFor();
  const text=await page.locator('#content').innerText();
  assert.doesNotMatch(text,/\b(Permission|Protected|Assigned roles|State|Revoke|Deactivate|School default|Allowed|Disabled|Type \/ parent|Details|association|session\.demo_login)\b/,`English UI in ${tab}`);
 }
 await page.getByRole('button',{name:'Đơn vị',exact:true}).click();
 await page.getByRole('button',{name:'Đơn vị mới',exact:true}).click();
 await page.locator('#unit-form [name=type]').selectOption('office');
 assert.equal(await page.locator('#unit-form [name=type]').inputValue(),'office','translation must preserve submitted enums');
 assert.equal(await page.locator('#unit-form [name=type] option:checked').innerText(),'Văn phòng');
 await page.getByRole('button',{name:'Đóng hộp thoại',exact:true}).click();
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Vietnamese admin mobile overflow');
 const fresh=await browser.newPage();
 await fresh.goto(base);await fresh.getByRole('button',{name:'Đăng nhập',exact:true}).waitFor();
 assert.equal(await fresh.locator('html').getAttribute('lang'),'vi');
 assert.doesNotMatch(await fresh.locator('body').innerText(),/Everyday work|Shared purpose|WELCOME TO|Pick a role|School of Electrical/);
 await fresh.locator('#login-form [name=password]').fill('incorrect-password');
 await fresh.getByRole('button',{name:'Đăng nhập',exact:true}).click();
 await fresh.getByText('Địa chỉ thư điện tử hoặc mật khẩu không đúng.',{exact:true}).waitFor();
 await fresh.close();
 assert.deepEqual(errors,[]);console.log('Browser checks passed: draft → approval, Leader appointment, Dean restrictions, Admin workflows/export, desktop/mobile and language switch.');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(server)await new Promise(r=>server.close(r));if(app)await app.close();if(root)await root.end();});
