require('dotenv').config();
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');
const express = require('express');
const helmet = require('helmet');
const session = require('express-session');
const MySQLStore = require('express-mysql-session')(session);
const mysql = require('mysql2/promise');
const bcrypt = require('bcryptjs');
const multer = require('multer');
const packageInfo = require('../package.json');
const logger = require('./logger');

const app = express();
const port = Number(process.env.PORT || 3000);
const isProduction=process.env.NODE_ENV==='production';
const requiredProductionKeys=['DB_HOST','DB_NAME','DB_USER','DB_PASSWORD','SESSION_SECRET'];
const missingProductionKeys=requiredProductionKeys.filter(key=>!process.env[key]);
if(isProduction&&missingProductionKeys.length)console.warn(`Configuration warning: missing ${missingProductionKeys.join(', ')}. Configure these in cPanel, then restart the application.`);
if(isProduction&&process.env.SESSION_SECRET&&process.env.SESSION_SECRET.length<32)console.warn('Configuration warning: SESSION_SECRET should contain at least 32 characters.');
const dbConfig = { host:process.env.DB_HOST||'localhost',port:Number(process.env.DB_PORT||3306),user:process.env.DB_USER||'seee_app',password:process.env.DB_PASSWORD||'',database:process.env.DB_NAME||'seee_activity_hub',charset:'utf8mb4',waitForConnections:true,connectionLimit:10 };
const db = mysql.createPool(dbConfig);
const hasConfiguredDatabase=['DB_NAME','DB_USER','DB_PASSWORD'].every(key=>Boolean(process.env[key]));
const sessionSecret=process.env.SESSION_SECRET||crypto.randomBytes(32).toString('hex');
const attachmentRoot=path.join(__dirname,'..','storage','task-attachments');
fs.mkdirSync(attachmentRoot,{recursive:true});
const taskUpload=multer({storage:multer.memoryStorage(),limits:{fileSize:50*1024*1024,files:1}});
const attachmentKinds=['clarification','evidence','issue','deliverable'];
const allowedExtensions=new Set(['.jpg','.jpeg','.png','.gif','.webp','.heic','.pdf','.doc','.docx','.xls','.xlsx','.ppt','.pptx','.txt','.csv','.zip']);

app.set('trust proxy',1);
app.use(helmet({contentSecurityPolicy:false}));
app.use(express.json({limit:'1mb'}));
app.use(express.urlencoded({extended:false}));
const sessionOptions={name:'seee.sid',secret:sessionSecret,resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:isProduction,maxAge:43200000}};
if(hasConfiguredDatabase)sessionOptions.store=new MySQLStore(dbConfig);
app.use(session(sessionOptions));
app.use(express.static(path.join(__dirname,'..','public')));
const applicationShell=path.join(__dirname,'..','public','index.html');

const asyncRoute=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
const auth=(req,res,next)=>req.session.user?next():res.status(401).json({error:'Please sign in to continue.'});
const admin=(req,res,next)=>req.session.user?.role==='admin'?next():res.status(403).json({error:'Administrator access is required.'});
const manager=(req,res,next)=>['admin','leader'].includes(req.session.user?.role)?next():res.status(403).json({error:'You do not have permission for this action.'});
const one=rows=>rows[0]||null;
const ids=value=>[...new Set((Array.isArray(value)?value:[value]).map(Number).filter(Number.isInteger))];

function activityScope(user,alias='a'){
  if(user.role==='admin') return {sql:'1=1',params:[]};
  if(user.role==='leader') return {sql:`(${alias}.creator_id=? OR EXISTS(SELECT 1 FROM activity_teams sat JOIN user_teams sut ON sut.team_id=sat.team_id WHERE sat.activity_id=${alias}.id AND sut.user_id=? AND sut.is_lead=1))`,params:[user.id,user.id]};
  return {sql:`(EXISTS(SELECT 1 FROM participants sp WHERE sp.activity_id=${alias}.id AND sp.user_id=? AND sp.state!='declined') OR EXISTS(SELECT 1 FROM tasks st JOIN task_assignees sta ON sta.task_id=st.id WHERE st.activity_id=${alias}.id AND sta.user_id=?) OR EXISTS(SELECT 1 FROM activity_teams sat JOIN user_teams sut ON sut.team_id=sat.team_id WHERE sat.activity_id=${alias}.id AND sut.user_id=?))`,params:[user.id,user.id,user.id]};
}
async function leadsTeam(userId,teamId){const [r]=await db.execute('SELECT 1 FROM user_teams WHERE user_id=? AND team_id=? AND is_lead=1',[userId,teamId]);return !!r.length}
async function canManageTeam(user,teamId){return user.role==='admin'||(user.role==='leader'&&await leadsTeam(user.id,teamId))}
async function canManageActivity(user,activityId){if(user.role==='admin')return true;const [r]=await db.execute('SELECT 1 FROM activities a JOIN activity_teams at ON at.activity_id=a.id JOIN user_teams ut ON ut.team_id=at.team_id WHERE a.id=? AND (a.creator_id=? OR (ut.user_id=? AND ut.is_lead=1)) LIMIT 1',[activityId,user.id,user.id]);return !!r.length}
async function visibleActivity(user,activityId){const s=activityScope(user);const [r]=await db.execute(`SELECT 1 FROM activities a WHERE a.id=? AND ${s.sql}`,[activityId,...s.params]);return !!r.length}

app.get('/api/session',(req,res)=>res.json({user:req.session.user||null}));
app.get('/api/version',(_req,res)=>res.json({version:packageInfo.version,build:'2026-08-12.2'}));
app.get('/api/health',asyncRoute(async(_req,res)=>{try{await db.query('SELECT 1');res.json({status:'ok'})}catch(error){logger.error('Database health check failed.',error);throw error}}));
app.post('/api/login',asyncRoute(async(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase();const [rows]=await db.execute('SELECT id,name,email,password_hash,role,avatar_color FROM users WHERE email=? AND is_active=1',[email]);const user=one(rows);if(!user||!(await bcrypt.compare(String(req.body.password||''),user.password_hash)))return res.status(401).json({error:'Email or password is incorrect.'});delete user.password_hash;req.session.user=user;res.json({user})}));
app.post('/api/logout',(req,res,next)=>req.session.destroy(err=>err?next(err):res.json({ok:true})));

app.get('/api/bootstrap',auth,asyncRoute(async(req,res)=>{
  const user=req.session.user,s=activityScope(user);
  const taskScope=user.role==='admin'?'1=1':user.role==='leader'?`(EXISTS(SELECT 1 FROM user_teams x WHERE x.user_id=? AND x.team_id=t.team_id AND x.is_lead=1) OR EXISTS(SELECT 1 FROM task_assignees x WHERE x.task_id=t.id AND x.user_id=?))`:`EXISTS(SELECT 1 FROM task_assignees x WHERE x.task_id=t.id AND x.user_id=?)`;
  const taskParams=user.role==='admin'?[]:user.role==='leader'?[user.id,user.id]:[user.id];
  const [[statRows],[upcoming],[tasks],[activity],[teams]]=await Promise.all([
    db.execute(`SELECT COUNT(DISTINCT CASE WHEN a.status IN ('approved','active') THEN a.id END) activeActivities,COUNT(DISTINCT CASE WHEN t.status!='done' THEN t.id END) openTasks,COUNT(DISTINCT CASE WHEN t.status!='done' AND t.deadline<CURDATE() THEN t.id END) overdueTasks,COUNT(DISTINCT CASE WHEN t.status='done' AND MONTH(t.completed_at)=MONTH(CURDATE()) AND YEAR(t.completed_at)=YEAR(CURDATE()) THEN t.id END) completedMonth FROM activities a LEFT JOIN tasks t ON t.activity_id=a.id WHERE ${s.sql}`,s.params),
    db.execute(`SELECT a.*,te.name team_name,te.color team_color,GROUP_CONCAT(DISTINCT involved.name ORDER BY involved.name SEPARATOR ', ') team_names,COUNT(DISTINCT t.id) task_count,COUNT(DISTINCT CASE WHEN t.status='done' THEN t.id END) done_count,COUNT(DISTINCT p.user_id) participant_count FROM activities a JOIN teams te ON te.id=a.team_id JOIN activity_teams ats ON ats.activity_id=a.id JOIN teams involved ON involved.id=ats.team_id LEFT JOIN tasks t ON t.activity_id=a.id LEFT JOIN participants p ON p.activity_id=a.id AND p.state='confirmed' WHERE a.status IN ('proposed','approved','active') AND ${s.sql} GROUP BY a.id ORDER BY a.deadline LIMIT 5`,s.params),
    db.execute(`SELECT t.*,a.title activity_title,te.name team_name,GROUP_CONCAT(DISTINCT u.name ORDER BY u.name SEPARATOR ', ') assignee_name,GROUP_CONCAT(DISTINCT u.id ORDER BY u.id) assignee_ids FROM tasks t JOIN activities a ON a.id=t.activity_id JOIN teams te ON te.id=t.team_id LEFT JOIN task_assignees ta ON ta.task_id=t.id LEFT JOIN users u ON u.id=ta.user_id WHERE ${taskScope} AND t.status!='done' GROUP BY t.id ORDER BY t.deadline LIMIT 8`,taskParams),
    db.execute(`SELECT n.body,n.kind,n.created_at,usr.name user_name,usr.avatar_color,a.title activity_title,a.id activity_id FROM updates n JOIN users usr ON usr.id=n.user_id JOIN activities a ON a.id=n.activity_id WHERE ${s.sql} ORDER BY n.created_at DESC LIMIT 7`,s.params),
    db.execute(`SELECT t.*,EXISTS(SELECT 1 FROM user_teams ux WHERE ux.team_id=t.id AND ux.user_id=? AND ux.is_lead=1) can_manage FROM teams t WHERE t.is_active=1 ORDER BY t.sort_order,t.name`,[user.id])
  ]);
  res.json({stats:one(statRows),upcoming,tasks,activity,teams,capabilities:{canCreateActivity:['admin','leader'].includes(user.role),canCreateAccount:user.role==='admin'}})
}));

app.get('/api/activities',auth,asyncRoute(async(req,res)=>{const q=`%${String(req.query.q||'')}%`,status=String(req.query.status||'all'),type=String(req.query.type||'all'),s=activityScope(req.session.user);const [rows]=await db.execute(`SELECT a.*,te.name team_name,te.color team_color,u.name creator_name,GROUP_CONCAT(DISTINCT involved.name ORDER BY involved.name SEPARATOR ', ') team_names,COUNT(DISTINCT t.id) task_count,COUNT(DISTINCT CASE WHEN t.status='done' THEN t.id END) done_count,COUNT(DISTINCT p.user_id) participant_count FROM activities a JOIN teams te ON te.id=a.team_id JOIN users u ON u.id=a.creator_id JOIN activity_teams ats ON ats.activity_id=a.id JOIN teams involved ON involved.id=ats.team_id LEFT JOIN tasks t ON t.activity_id=a.id LEFT JOIN participants p ON p.activity_id=a.id AND p.state='confirmed' WHERE ${s.sql} AND (a.title LIKE ? OR a.description LIKE ?) AND (?='all' OR a.status=?) AND (?='all' OR a.type=?) GROUP BY a.id ORDER BY FIELD(a.status,'active','approved','proposed','completed','cancelled'),a.deadline`,[...s.params,q,q,status,status,type,type]);res.json(rows)}));

app.post('/api/activities',auth,manager,asyncRoute(async(req,res)=>{const {title,description,type,start_date,deadline,priority,requested_by,location}=req.body;const teamIds=ids(req.body.team_ids?.length?req.body.team_ids:req.body.team_id),primary=Number(req.body.team_id||teamIds[0]);if(!title||!description||!deadline||!teamIds.length||!teamIds.includes(primary)||!['event','assigned'].includes(type))return res.status(400).json({error:'Complete all required fields and select at least one team.'});if(req.session.user.role==='leader'){for(const teamId of teamIds)if(!(await leadsTeam(req.session.user.id,teamId)))return res.status(403).json({error:'Team leaders may only propose work for teams they lead.'})}const conn=await db.getConnection();try{await conn.beginTransaction();const [result]=await conn.execute('INSERT INTO activities(title,description,type,team_id,creator_id,start_date,deadline,priority,requested_by,location) VALUES(?,?,?,?,?,?,?,?,?,?)',[title,description,type,primary,req.session.user.id,start_date||null,deadline,priority||'medium',requested_by||null,location||null]);for(const teamId of teamIds)await conn.execute('INSERT INTO activity_teams(activity_id,team_id,role,responsibility) VALUES(?,?,?,?)',[result.insertId,teamId,teamId===primary?'primary':'supporting',teamId===primary?'Coordinates the activity':'Supports the activity']);await conn.commit();res.status(201).json({id:result.insertId})}catch(e){await conn.rollback();throw e}finally{conn.release()}}));

app.get('/api/activities/:id',auth,asyncRoute(async(req,res)=>{if(!(await visibleActivity(req.session.user,req.params.id)))return res.status(404).json({error:'Activity not found.'});const [[activities],[activityTeams],[tasks],[participants],[updates],[people],[attachments]]=await Promise.all([
  db.execute('SELECT a.*,te.name team_name,te.color team_color,u.name creator_name FROM activities a JOIN teams te ON te.id=a.team_id JOIN users u ON u.id=a.creator_id WHERE a.id=?',[req.params.id]),
  db.execute('SELECT at.*,t.name,t.color,u.name contact_name FROM activity_teams at JOIN teams t ON t.id=at.team_id LEFT JOIN users u ON u.id=at.contact_user_id WHERE at.activity_id=? ORDER BY at.role,t.name',[req.params.id]),
  db.execute(`SELECT t.*,te.name team_name,GROUP_CONCAT(DISTINCT u.name ORDER BY u.name SEPARATOR ', ') assignee_name,GROUP_CONCAT(DISTINCT u.id ORDER BY u.id) assignee_ids FROM tasks t JOIN teams te ON te.id=t.team_id LEFT JOIN task_assignees ta ON ta.task_id=t.id LEFT JOIN users u ON u.id=ta.user_id WHERE t.activity_id=? GROUP BY t.id ORDER BY FIELD(t.stage,'before','during','after','general'),t.deadline`,[req.params.id]),
  db.execute("SELECT p.*,u.name,u.role,u.avatar_color FROM participants p JOIN users u ON u.id=p.user_id WHERE p.activity_id=? ORDER BY FIELD(p.state,'confirmed','volunteered','declined'),u.name",[req.params.id]),
  db.execute('SELECT n.*,u.name user_name,u.avatar_color FROM updates n JOIN users u ON u.id=n.user_id WHERE n.activity_id=? ORDER BY n.created_at DESC',[req.params.id]),
  db.execute('SELECT DISTINCT u.id,u.name,u.role,ut.team_id FROM users u JOIN user_teams ut ON ut.user_id=u.id JOIN activity_teams at ON at.team_id=ut.team_id WHERE at.activity_id=? AND u.is_active=1 ORDER BY u.name',[req.params.id]),
  db.execute('SELECT x.id,x.task_id,x.kind,x.label,x.link_url,x.original_name,x.mime_type,x.size_bytes,x.created_at,u.name user_name FROM task_attachments x JOIN users u ON u.id=x.user_id JOIN tasks t ON t.id=x.task_id WHERE t.activity_id=? ORDER BY x.created_at DESC',[req.params.id])
]);res.json({activity:activities[0],activityTeams,tasks,participants,updates,people,attachments,canManage:await canManageActivity(req.session.user,req.params.id)})}));

app.patch('/api/activities/:id',auth,manager,asyncRoute(async(req,res)=>{if(!(await canManageActivity(req.session.user,req.params.id)))return res.status(403).json({error:'You cannot manage this activity.'});const allowed=['status','priority','result_summary','title','description','deadline','start_date','location'];const entries=Object.entries(req.body).filter(([key])=>allowed.includes(key));if(!entries.length)return res.status(400).json({error:'No valid fields supplied.'});await db.execute(`UPDATE activities SET ${entries.map(([k])=>`${k}=?`).join(',')} WHERE id=?`,[...entries.map(([,v])=>v||null),req.params.id]);res.json({ok:true})}));
app.post('/api/activities/:id/volunteer',auth,asyncRoute(async(req,res)=>{if(!(await visibleActivity(req.session.user,req.params.id)))return res.status(404).json({error:'Activity not found.'});await db.execute("INSERT INTO participants(activity_id,user_id,state) VALUES(?,?,'volunteered') ON DUPLICATE KEY UPDATE state='volunteered'",[req.params.id,req.session.user.id]);res.json({ok:true})}));
app.post('/api/activities/:id/updates',auth,asyncRoute(async(req,res)=>{if(!(await visibleActivity(req.session.user,req.params.id)))return res.status(404).json({error:'Activity not found.'});if(!String(req.body.body||'').trim())return res.status(400).json({error:'Write an update first.'});await db.execute('INSERT INTO updates(activity_id,task_id,user_id,body,kind,attachment_url) VALUES(?,?,?,?,?,?)',[req.params.id,req.body.task_id||null,req.session.user.id,req.body.body,req.body.kind||'comment',req.body.attachment_url||null]);res.status(201).json({ok:true})}));

app.post('/api/activities/:id/tasks',auth,manager,asyncRoute(async(req,res)=>{if(!(await canManageActivity(req.session.user,req.params.id)))return res.status(403).json({error:'You cannot manage this activity.'});const {title,description,stage,priority,team_id,start_date,deadline,deliverable}=req.body,assigneeIds=ids(req.body.assignee_ids?.length?req.body.assignee_ids:req.body.assignee_id);if(!title||!team_id||!deadline)return res.status(400).json({error:'Title, team and deadline are required.'});if(!(await canManageTeam(req.session.user,team_id)))return res.status(403).json({error:'You cannot assign work for this team.'});for(const userId of assigneeIds){const [member]=await db.execute('SELECT 1 FROM user_teams WHERE user_id=? AND team_id=?',[userId,team_id]);if(!member.length)return res.status(400).json({error:'Every assignee must belong to the responsible team.'})}const conn=await db.getConnection();try{await conn.beginTransaction();const [result]=await conn.execute('INSERT INTO tasks(activity_id,title,description,stage,priority,team_id,assignee_id,start_date,deadline,deliverable) VALUES(?,?,?,?,?,?,?,?,?,?)',[req.params.id,title,description||null,stage||'general',priority||'medium',team_id,assigneeIds[0]||null,start_date||null,deadline,deliverable||null]);for(const userId of assigneeIds)await conn.execute('INSERT INTO task_assignees(task_id,user_id) VALUES(?,?)',[result.insertId,userId]);await conn.execute("INSERT IGNORE INTO activity_teams(activity_id,team_id,role,responsibility) VALUES(?,?,'supporting','Responsible for assigned work')",[req.params.id,team_id]);await conn.commit();res.status(201).json({id:result.insertId})}catch(e){await conn.rollback();throw e}finally{conn.release()}}));

app.patch('/api/tasks/:id',auth,asyncRoute(async(req,res)=>{const [rows]=await db.execute('SELECT t.*,EXISTS(SELECT 1 FROM task_assignees ta WHERE ta.task_id=t.id AND ta.user_id=?) assigned_to_me FROM tasks t WHERE t.id=?',[req.session.user.id,req.params.id]);const task=one(rows);if(!task)return res.status(404).json({error:'Task not found.'});const manages=await canManageTeam(req.session.user,task.team_id);if(!manages&&!task.assigned_to_me)return res.status(403).json({error:'You cannot update this task.'});const allowed=manages?['status','deadline','start_date','priority','deliverable']:['status'];const entries=Object.entries(req.body).filter(([key])=>allowed.includes(key));if(!entries.length)return res.status(400).json({error:'No valid fields supplied.'});const complete=entries.find(([k])=>k==='status')?.[1]==='done'?',completed_at=NOW()':'';await db.execute(`UPDATE tasks SET ${entries.map(([k])=>`${k}=?`).join(',')}${complete} WHERE id=?`,[...entries.map(([,v])=>v||null),req.params.id]);res.json({ok:true})}));

app.get('/api/people',auth,asyncRoute(async(req,res)=>{let scope='1=1',params=[];if(req.session.user.role==='leader'){scope='EXISTS(SELECT 1 FROM user_teams mine JOIN user_teams theirs ON theirs.team_id=mine.team_id WHERE mine.user_id=? AND mine.is_lead=1 AND theirs.user_id=u.id)';params=[req.session.user.id]}else if(req.session.user.role==='member'){scope='u.id=?';params=[req.session.user.id]}const [rows]=await db.execute(`SELECT u.id,u.name,u.email,u.role,u.phone,u.avatar_color,u.is_active,GROUP_CONCAT(DISTINCT t.name ORDER BY t.name SEPARATOR ', ') teams,COUNT(DISTINCT CASE WHEN tk.status='done' THEN tk.id END) completed_tasks FROM users u LEFT JOIN user_teams ut ON ut.user_id=u.id LEFT JOIN teams t ON t.id=ut.team_id LEFT JOIN task_assignees ta ON ta.user_id=u.id LEFT JOIN tasks tk ON tk.id=ta.task_id WHERE u.is_active=1 AND ${scope} GROUP BY u.id ORDER BY FIELD(u.role,'admin','leader','member'),u.name`,params);res.json(rows)}));

app.post('/api/users',auth,admin,asyncRoute(async(req,res)=>{const {name,email,password,role,phone}=req.body,teamIds=ids(req.body.team_ids);if(!name||!email||!password||!['admin','leader','member'].includes(role))return res.status(400).json({error:'Name, email, password and role are required.'});if(role==='member'&&!teamIds.length)return res.status(400).json({error:'A member must belong to at least one team.'});if(password.length<8)return res.status(400).json({error:'Password must contain at least 8 characters.'});const conn=await db.getConnection();try{await conn.beginTransaction();const hash=await bcrypt.hash(password,10);const [result]=await conn.execute('INSERT INTO users(name,email,password_hash,role,phone) VALUES(?,?,?,?,?)',[name,String(email).trim().toLowerCase(),hash,role,phone||null]);for(const teamId of teamIds)await conn.execute('INSERT INTO user_teams(user_id,team_id,is_lead) VALUES(?,?,?)',[result.insertId,teamId,role==='leader']);await conn.commit();res.status(201).json({id:result.insertId})}catch(e){await conn.rollback();throw e}finally{conn.release()}}));

app.get('/api/teams',auth,asyncRoute(async(req,res)=>{const [rows]=await db.execute(`SELECT t.*,COUNT(DISTINCT ut.user_id) member_count,COUNT(DISTINCT CASE WHEN a.status IN ('approved','active') THEN ats.activity_id END) active_count,EXISTS(SELECT 1 FROM user_teams mine WHERE mine.team_id=t.id AND mine.user_id=? AND mine.is_lead=1) can_manage FROM teams t LEFT JOIN user_teams ut ON ut.team_id=t.id LEFT JOIN activity_teams ats ON ats.team_id=t.id LEFT JOIN activities a ON a.id=ats.activity_id WHERE t.is_active=1 GROUP BY t.id ORDER BY t.sort_order,t.name`,[req.session.user.id]);res.json(rows)}));
app.post('/api/teams',auth,admin,asyncRoute(async(req,res)=>{if(!req.body.name)return res.status(400).json({error:'Team name is required.'});const [result]=await db.execute('INSERT INTO teams(name,description,color) VALUES(?,?,?)',[req.body.name,req.body.description||null,req.body.color||'#315C4C']);res.status(201).json({id:result.insertId})}));
app.get('/api/teams/:id/members',auth,asyncRoute(async(req,res)=>{if(req.session.user.role!=='admin'&&!(await canManageTeam(req.session.user,req.params.id)))return res.status(403).json({error:'You cannot manage this team.'});const [[members],[available]]=await Promise.all([db.execute('SELECT u.id,u.name,u.email,u.role,u.avatar_color,ut.is_lead FROM user_teams ut JOIN users u ON u.id=ut.user_id WHERE ut.team_id=? AND u.is_active=1 ORDER BY ut.is_lead DESC,u.name',[req.params.id]),db.execute('SELECT u.id,u.name,u.email,u.role FROM users u WHERE u.is_active=1 AND NOT EXISTS(SELECT 1 FROM user_teams ut WHERE ut.user_id=u.id AND ut.team_id=?) ORDER BY u.name',[req.params.id])]);res.json({members,available})}));
app.get('/api/teams/:id/overview',auth,asyncRoute(async(req,res)=>{if(req.session.user.role!=='admin'&&!(await canManageTeam(req.session.user,req.params.id)))return res.status(403).json({error:'You cannot view this team overview.'});const [[teamRows],[members],[tasks],[activities]]=await Promise.all([db.execute(`SELECT t.*,COUNT(DISTINCT ut.user_id) member_count,COUNT(DISTINCT CASE WHEN tk.status!='done' THEN tk.id END) open_tasks,COUNT(DISTINCT CASE WHEN tk.status='done' THEN tk.id END) done_tasks,COUNT(DISTINCT CASE WHEN tk.status!='done' AND tk.deadline<CURDATE() THEN tk.id END) overdue_tasks FROM teams t LEFT JOIN user_teams ut ON ut.team_id=t.id LEFT JOIN tasks tk ON tk.team_id=t.id WHERE t.id=? GROUP BY t.id`,[req.params.id]),db.execute(`SELECT u.id,u.name,u.email,u.role,u.avatar_color,ut.is_lead,COUNT(DISTINCT CASE WHEN tk.status!='done' THEN ta.task_id END) open_tasks,COUNT(DISTINCT CASE WHEN tk.status='done' THEN ta.task_id END) done_tasks FROM user_teams ut JOIN users u ON u.id=ut.user_id LEFT JOIN task_assignees ta ON ta.user_id=u.id LEFT JOIN tasks tk ON tk.id=ta.task_id AND tk.team_id=ut.team_id WHERE ut.team_id=? AND u.is_active=1 GROUP BY u.id,ut.is_lead ORDER BY ut.is_lead DESC,u.name`,[req.params.id]),db.execute(`SELECT tk.*,a.title activity_title,GROUP_CONCAT(DISTINCT u.name ORDER BY u.name SEPARATOR ', ') assignee_name FROM tasks tk JOIN activities a ON a.id=tk.activity_id LEFT JOIN task_assignees ta ON ta.task_id=tk.id LEFT JOIN users u ON u.id=ta.user_id WHERE tk.team_id=? GROUP BY tk.id ORDER BY FIELD(tk.status,'in_progress','review','open','done'),tk.deadline LIMIT 50`,[req.params.id]),db.execute(`SELECT a.id,a.title,a.status,a.deadline,ats.role,COUNT(DISTINCT tk.id) task_count,COUNT(DISTINCT CASE WHEN tk.status='done' THEN tk.id END) done_count FROM activity_teams ats JOIN activities a ON a.id=ats.activity_id LEFT JOIN tasks tk ON tk.activity_id=a.id AND tk.team_id=ats.team_id WHERE ats.team_id=? GROUP BY a.id,ats.role ORDER BY FIELD(a.status,'active','approved','proposed','completed','cancelled'),a.deadline`,[req.params.id])]);if(!teamRows.length)return res.status(404).json({error:'Team not found.'});res.json({team:teamRows[0],members,tasks,activities})}));
app.post('/api/teams/:id/members',auth,manager,asyncRoute(async(req,res)=>{if(!(await canManageTeam(req.session.user,req.params.id)))return res.status(403).json({error:'You cannot manage this team.'});const userId=Number(req.body.user_id);const [users]=await db.execute('SELECT role FROM users WHERE id=? AND is_active=1',[userId]);if(!users.length)return res.status(404).json({error:'User not found.'});if(req.session.user.role==='leader'&&users[0].role!=='member')return res.status(403).json({error:'Team leaders may only add member accounts.'});const isLead=req.session.user.role==='admin'&&Boolean(req.body.is_lead);await db.execute('INSERT INTO user_teams(user_id,team_id,is_lead) VALUES(?,?,?) ON DUPLICATE KEY UPDATE is_lead=VALUES(is_lead)',[userId,req.params.id,isLead]);if(isLead&&users[0].role==='member')await db.execute("UPDATE users SET role='leader' WHERE id=?",[userId]);res.status(201).json({ok:true})}));

app.get('/api/archive',auth,asyncRoute(async(req,res)=>{const q=`%${String(req.query.q||'')}%`,s=activityScope(req.session.user);const [rows]=await db.execute(`SELECT a.*,te.name team_name,te.color team_color,u.name creator_name,GROUP_CONCAT(DISTINCT involved.name ORDER BY involved.name SEPARATOR ', ') team_names,COUNT(DISTINCT t.id) task_count,COUNT(DISTINCT t.id) done_count,COUNT(DISTINCT p.user_id) participant_count,MAX(n.created_at) last_update FROM activities a JOIN teams te ON te.id=a.team_id JOIN users u ON u.id=a.creator_id JOIN activity_teams ats ON ats.activity_id=a.id JOIN teams involved ON involved.id=ats.team_id LEFT JOIN tasks t ON t.activity_id=a.id LEFT JOIN participants p ON p.activity_id=a.id AND p.state='confirmed' LEFT JOIN updates n ON n.activity_id=a.id WHERE ${s.sql} AND a.status='completed' AND (a.title LIKE ? OR a.description LIKE ? OR COALESCE(a.result_summary,'') LIKE ?) GROUP BY a.id ORDER BY a.deadline DESC`,[...s.params,q,q,q]);res.json(rows)}));

app.post('/api/tasks/:id/attachments',auth,taskUpload.single('file'),asyncRoute(async(req,res)=>{const [tasks]=await db.execute('SELECT id,activity_id FROM tasks WHERE id=?',[req.params.id]);const task=one(tasks);if(!task||!(await visibleActivity(req.session.user,task.activity_id)))return res.status(404).json({error:'Task not found.'});const kind=attachmentKinds.includes(req.body.kind)?req.body.kind:'clarification';const linkUrl=String(req.body.link_url||'').trim();if(linkUrl&&!/^https?:\/\//i.test(linkUrl))return res.status(400).json({error:'Links must begin with http:// or https://.'});if(!req.file&&!linkUrl)return res.status(400).json({error:'Choose a file or provide a relevant link.'});let storedName=null;try{if(req.file){const ext=path.extname(req.file.originalname).toLowerCase();if(!allowedExtensions.has(ext))return res.status(415).json({error:'This file type is not supported.'});const [usageRows]=await db.execute('SELECT COALESCE(SUM(size_bytes),0) used FROM task_attachments WHERE task_id=?',[task.id]);if(Number(usageRows[0].used)+req.file.size>50*1024*1024)return res.status(413).json({error:'This task has reached its shared 50 MB upload limit.'});storedName=`${task.id}-${crypto.randomUUID()}${ext}`;await fs.promises.writeFile(path.join(attachmentRoot,storedName),req.file.buffer,{flag:'wx'})}const label=String(req.body.label||req.file?.originalname||linkUrl).trim().slice(0,180);const [result]=await db.execute('INSERT INTO task_attachments(task_id,user_id,kind,label,link_url,stored_name,original_name,mime_type,size_bytes) VALUES(?,?,?,?,?,?,?,?,?)',[task.id,req.session.user.id,kind,label,linkUrl||null,storedName,req.file?.originalname||null,req.file?.mimetype||null,req.file?.size||0]);res.status(201).json({id:result.insertId})}catch(e){if(storedName)await fs.promises.unlink(path.join(attachmentRoot,storedName)).catch(()=>{});throw e}}));

app.get('/api/task-attachments/:id/content',auth,asyncRoute(async(req,res)=>{const [rows]=await db.execute('SELECT x.*,t.activity_id FROM task_attachments x JOIN tasks t ON t.id=x.task_id WHERE x.id=?',[req.params.id]);const item=one(rows);if(!item||!item.stored_name||!(await visibleActivity(req.session.user,item.activity_id)))return res.status(404).json({error:'Attachment not found.'});const filePath=path.join(attachmentRoot,path.basename(item.stored_name));if(!fs.existsSync(filePath))return res.status(404).json({error:'Stored file not found.'});res.type(item.mime_type||'application/octet-stream');res.setHeader('Content-Disposition',`${String(item.mime_type||'').startsWith('image/')?'inline':'attachment'}; filename*=UTF-8''${encodeURIComponent(item.original_name)}`);res.sendFile(filePath)}));

app.get('/api/tasks/:id',auth,asyncRoute(async(req,res)=>{const [taskRows]=await db.execute(`SELECT t.*,a.title activity_title,a.description activity_description,a.status activity_status,a.deadline activity_deadline,te.name team_name,GROUP_CONCAT(DISTINCT u.name ORDER BY u.name SEPARATOR ', ') assignee_name,GROUP_CONCAT(DISTINCT u.id ORDER BY u.id) assignee_ids FROM tasks t JOIN activities a ON a.id=t.activity_id JOIN teams te ON te.id=t.team_id LEFT JOIN task_assignees ta ON ta.task_id=t.id LEFT JOIN users u ON u.id=ta.user_id WHERE t.id=? GROUP BY t.id`,[req.params.id]);const task=one(taskRows);if(!task||!(await visibleActivity(req.session.user,task.activity_id)))return res.status(404).json({error:'Task not found.'});const [[attachments],[updates]]=await Promise.all([db.execute('SELECT x.id,x.task_id,x.kind,x.label,x.link_url,x.original_name,x.mime_type,x.size_bytes,x.created_at,u.name user_name FROM task_attachments x JOIN users u ON u.id=x.user_id WHERE x.task_id=? ORDER BY x.created_at DESC',[task.id]),db.execute('SELECT n.*,u.name user_name,u.avatar_color FROM updates n JOIN users u ON u.id=n.user_id WHERE n.task_id=? ORDER BY n.created_at DESC',[task.id])]);const assigned=String(task.assignee_ids||'').split(',').map(Number).includes(req.session.user.id),manages=await canManageTeam(req.session.user,task.team_id);res.json({task,attachments,updates,canUpdate:assigned||manages})}));

app.use('/api',(_req,res)=>res.status(404).json({error:'Endpoint not found.'}));
app.get(/.*/,(_req,res)=>res.sendFile(applicationShell));
app.use((err,req,res,_next)=>{logger.error(`${req.method} ${req.originalUrl} failed.`,err);console.error(err);if(res.headersSent)return;if(err instanceof multer.MulterError)return res.status(err.code==='LIMIT_FILE_SIZE'?413:400).json({error:err.code==='LIMIT_FILE_SIZE'?'A single file cannot exceed 50 MB.':err.message});res.status(err.code==='ER_DUP_ENTRY'?409:500).json({error:err.code==='ER_DUP_ENTRY'?'That item already exists.':'Something went wrong. Please try again.'})});
const server=app.listen(port,()=>{logger.info(`SEEE Activity Hub v${packageInfo.version} started on port ${port}.`);console.log(`SEEE Activity Hub running on port ${port}`)});
server.on('error',error=>{logger.error(`HTTP server could not start on port ${port}.`,error);console.error(error)});
process.on('uncaughtException',error=>{logger.error('Uncaught exception terminated the application.',error);console.error(error);process.exit(1)});
process.on('unhandledRejection',reason=>{logger.error('Unhandled promise rejection.',reason);console.error(reason)});
const shutdown=signal=>{logger.info(`Application received ${signal}; shutting down.`);server.close(()=>db.end().finally(()=>process.exit(0)))};
process.once('SIGTERM',()=>shutdown('SIGTERM'));
process.once('SIGINT',()=>shutdown('SIGINT'));
